// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SheetData represents data from a processed sheet
 */
export class SheetData {
    /**
     * Creates a new SheetData instance.
     * @param {Partial<SheetData>} [$$source = {}] - The source object to create the SheetData.
     */
    constructor($$source = {}) {
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["headers"] = [];
        }
        if (!("dataRows" in $$source)) {
            /**
             * @member
             * @type {any[][]}
             */
            this["dataRows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SheetData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SheetData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField0_0($$parsedSource["headers"]);
        }
        if ("dataRows" in $$parsedSource) {
            $$parsedSource["dataRows"] = $$createField1_0($$parsedSource["dataRows"]);
        }
        return new SheetData(/** @type {Partial<SheetData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType1);
