// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as excel$0 from "./internal/excel/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate checks GitHub for newer versions
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckForUpdate() {
    return $Call.ByID(2347956003).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CopyToClipboard copies text to the clipboard
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function CopyToClipboard(text) {
    return $Call.ByID(1438304177, text);
}

/**
 * FindAndReplace replaces values in the data rows
 * @param {any[][]} dataRows
 * @param {string} findValue
 * @param {string} replaceWith
 * @returns {$CancellablePromise<any[][]>}
 */
export function FindAndReplace(dataRows, findValue, replaceWith) {
    return $Call.ByID(3489523357, dataRows, findValue, replaceWith).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GenerateAndSaveSQL streams data from Excel directly to a SQL file
 * This is memory efficient (O(1)) and can handle massive files
 * @param {string} filePath
 * @param {string} sheetName
 * @param {string[]} headers
 * @param {string[]} numberColumns
 * @param {$models.Replacement[]} replacements
 * @returns {$CancellablePromise<boolean>}
 */
export function GenerateAndSaveSQL(filePath, sheetName, headers, numberColumns, replacements) {
    return $Call.ByID(2044828258, filePath, sheetName, headers, numberColumns, replacements);
}

/**
 * GenerateSQL generates SQL INSERT values from the data
 * @param {string[]} headers
 * @param {any[][]} dataRows
 * @param {string[]} numberColumns
 * @returns {$CancellablePromise<string>}
 */
export function GenerateSQL(headers, dataRows, numberColumns) {
    return $Call.ByID(3077652598, headers, dataRows, numberColumns);
}

/**
 * GetCurrentVersion returns the current app version
 * @returns {$CancellablePromise<string>}
 */
export function GetCurrentVersion() {
    return $Call.ByID(1827245900);
}

/**
 * OpenExcelFile opens a file dialog and parses the selected Excel file
 * @returns {$CancellablePromise<$models.ExcelResult | null>}
 */
export function OpenExcelFile() {
    return $Call.ByID(4212112218).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * OpenReleaseURL opens the release page in the default browser
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleaseURL(url) {
    return $Call.ByID(1293205979, url);
}

/**
 * PerformUpdate downloads and installs the new version (Windows only)
 * @param {string} downloadURL
 * @returns {$CancellablePromise<boolean>}
 */
export function PerformUpdate(downloadURL) {
    return $Call.ByID(1736600371, downloadURL);
}

/**
 * ProcessSheet reads data from a specific sheet
 * @param {string} filePath
 * @param {string} sheetName
 * @returns {$CancellablePromise<excel$0.SheetData | null>}
 */
export function ProcessSheet(filePath, sheetName) {
    return $Call.ByID(2663837021, filePath, sheetName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.ExcelResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = excel$0.SheetData.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
