// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExcelResult represents the result of opening an Excel file
 */
export class ExcelResult {
    /**
     * Creates a new ExcelResult instance.
     * @param {Partial<ExcelResult>} [$$source = {}] - The source object to create the ExcelResult.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("sheetNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["sheetNames"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExcelResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExcelResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sheetNames" in $$parsedSource) {
            $$parsedSource["sheetNames"] = $$createField1_0($$parsedSource["sheetNames"]);
        }
        return new ExcelResult(/** @type {Partial<ExcelResult>} */($$parsedSource));
    }
}

/**
 * Replacement defines a find-and-replace rule
 */
export class Replacement {
    /**
     * Creates a new Replacement instance.
     * @param {Partial<Replacement>} [$$source = {}] - The source object to create the Replacement.
     */
    constructor($$source = {}) {
        if (!("find" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["find"] = "";
        }
        if (!("replace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["replace"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Replacement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Replacement}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Replacement(/** @type {Partial<Replacement>} */($$parsedSource));
    }
}

/**
 * SQLOptions defines configuration for generating SQL statements
 */
export class SQLOptions {
    /**
     * Creates a new SQLOptions instance.
     * @param {Partial<SQLOptions>} [$$source = {}] - The source object to create the SQLOptions.
     */
    constructor($$source = {}) {
        if (!("tableName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tableName"] = "";
        }
        if (!("selectedColumns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["selectedColumns"] = [];
        }
        if (!("numberColumns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["numberColumns"] = [];
        }
        if (!("batchSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["batchSize"] = 0;
        }
        if (!("valuesOnly" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valuesOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SQLOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SQLOptions}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selectedColumns" in $$parsedSource) {
            $$parsedSource["selectedColumns"] = $$createField1_0($$parsedSource["selectedColumns"]);
        }
        if ("numberColumns" in $$parsedSource) {
            $$parsedSource["numberColumns"] = $$createField2_0($$parsedSource["numberColumns"]);
        }
        return new SQLOptions(/** @type {Partial<SQLOptions>} */($$parsedSource));
    }
}

/**
 * UpdateInfo holds information about available updates
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("currentVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latestVersion"] = "";
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }
        if (!("releaseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["releaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
