// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ExportToFile(arg1) {
  return window['go']['main']['App']['ExportToFile'](arg1);
}

export function FindAndReplace(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindAndReplace'](arg1, arg2, arg3);
}

export function GenerateSQL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSQL'](arg1, arg2, arg3);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function OpenExcelFile() {
  return window['go']['main']['App']['OpenExcelFile']();
}

export function OpenReleaseURL(arg1) {
  return window['go']['main']['App']['OpenReleaseURL'](arg1);
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function ProcessSheet(arg1, arg2) {
  return window['go']['main']['App']['ProcessSheet'](arg1, arg2);
}
