// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function ExportToFile(arg1:string):Promise<void>;

export function FindAndReplace(arg1:Array<any>,arg2:string,arg3:string):Promise<Array<any>>;

export function GenerateSQL(arg1:Array<string>,arg2:Array<any>,arg3:Array<string>):Promise<string>;

export function OpenExcelFile():Promise<main.ExcelResult>;

export function ProcessSheet(arg1:string,arg2:string):Promise<main.SheetData>;
