// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function ExportToFile(arg1:string):Promise<void>;

export function FindAndReplace(arg1:Array<any>,arg2:string,arg3:string):Promise<Array<any>>;

export function GenerateAndSaveSQL(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:Array<main.Replacement>):Promise<void>;

export function GenerateSQL(arg1:Array<string>,arg2:Array<any>,arg3:Array<string>):Promise<string>;

export function GetCurrentVersion():Promise<string>;

export function OpenExcelFile():Promise<main.ExcelResult>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function PerformUpdate(arg1:string):Promise<boolean>;

export function ProcessSheet(arg1:string,arg2:string):Promise<main.SheetData>;
